apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-mpnunxxk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/go-mpnunxxk:bf8c7987236e165cf3726ca30480188ed6ebd863@sha256:ed1aaeba1bd7a794943b381f882ecc74648d80da1b9fb5894f97d8ed47daced4
          name: container-image
